version: "3"
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongodb
    restart: unless-stopped
    expose:
      - "27017" # process
      - "28017" # http
    ports:
      - "127.0.0.1:27017:27017"
      - "127.0.0.1:28017:28017"
  dataws:
    env_file:
      - config.env
    build:
      context: .
      dockerfile: Dockerfile.dataws
    ports:
      - "5000:5000"
    restart: unless-stopped
    links: 
      - mongodb